### ISSUE TITLE
The terraform-provider-vcd_v3.3.1 plugin crashed

### ISSUE THREAD

**Issue by easokol** [vmware/terraform-provider-vcd#710]
### Terraform Version
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.3.1

### Affected Resource(s)
- vcd_network_routed

### Terraform Configuration Files
```hcl
resource "vcd_network_routed" "rnet" {
  name         = "tf-demo-r-net-01"
  vdc          = var.vcd_vdc
  edge_gateway = "MYGW"
  gateway      = "10.10.0.1"

  dhcp_pool {
    start_address = "10.10.0.2"
    end_address   = "10.10.0.100"
  }

  static_ip_pool {
    start_address = "10.10.0.152"
    end_address   = "10.10.0.254"
  }
}
```

### Debug Output
```shell
Stack trace from the terraform-provider-vcd_v3.3.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb08471]

goroutine 60 [running]:
github.com/vmware/go-vcloud-director/v2/govcd.(*EdgeGateway).AddDhcpPool(0xc0003172f0, 0xc0004f8600, 0xc00069a550, 0x1, 0x1, 0x1, 0x0, 0x0, 0xc000617e60)
        github.com/vmware/go-vcloud-director/v2@v2.12.1/govcd/edgegateway.go:76 +0x1f1
github.com/vmware/terraform-provider-vcd/v3/vcd.resourceVcdNetworkRoutedCreate(0xc0002e8100, 0xea6240, 0xc00069fa90, 0x0, 0x0)
        github.com/vmware/terraform-provider-vcd/v3/vcd/resource_vcd_network_routed.go:271 +0xc72
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002f8600, 0xff1ea8, 0xc0000faa80, 0xc0002e8100, 0xea6240, 0xc00069fa90, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:278 +0x88
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002f8600, 0xff1ea8, 0xc0000faa80, 0xc00035e310, 0xc000617e60, 0xea6240, 0xc00069fa90, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:396 +0x674
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000288798, 0xff1ea8, 0xc0000faa80, 0xc00029b680, 0xc0000faa80, 0xe6b7c0, 0xc00016a200)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000322e80, 0xff1f50, 0xc0000faa80, 0xc00035e070, 0xc000322e80, 0xc00016a240, 0xc000257ba0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xe6b7c0, 0xc000322e80, 0xff1f50, 0xc00016a240, 0xc000115b00, 0x0, 0xff1f50, 0xc00016a240, 0xc00027d180, 0x305)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fcc40, 0xffb778, 0xc000103500, 0xc00012ed00, 0xc00047a540, 0x14a7840, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001fcc40, 0xffb778, 0xc000103500, 0xc00012ed00, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00028c220, 0xc0001fcc40, 0xffb778, 0xc000103500, 0xc00012ed00)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-vcd_v3.3.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by Didainius** [comment]
Hello,
While the crash is not a good thing - could you try to use `vcd_network_routed_v2`? (https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/network_routed_v2)

**Comment by Didainius** [comment]
The bug you mentioned is probably #559

**Comment by easokol** [comment]
If I understand correctly, the DHCP pool cannot be added for VCD Routed Network due to VCD specs, so `vcd_network_routed` with `dhcp pool` enabled cannot work at all. In that case it does not matter which resource to be used for Routed Network.

**Comment by Didainius** [comment]
We are not investing to NSX-V anymore. NSX-T has a separate resource for DHCP handling
